### ISSUE TITLE
Rotating image in example app seems not to work

### ISSUE THREAD

**Issue by leijdekkers** [Vong3432/interactive_box#3]
Nice library! I am testing the example app on a mobile device but i seem not be able to rotate the 'table' image when i tap the rotate button and use two fingers to rotate the image. Does it work and if so how do you rotate an image on a mobile device with your fingers in this case?

UPDATE:  okay got it working on my own app using my own image and using a basic instance of the InteractiveBox. Maybe something wrong with the sample app?

UPDATE2:  seems to work okay. The "green" rotating icon is actually hidden behind the button to activate rotation. Maybe a suggestion  to position the green rotating icon never behind one of the buttons to control the interactivebox!

**Comment by Vong3432** [comment]
> UPDATE: okay got it working on my own app using my own image and using a basic instance of the InteractiveBox. Maybe something wrong with the sample app?

I think it is because it conflicted with the gesture detection of the SingleChildScrollView in the example snippet.

> UPDATE2: seems to work okay. The "green" rotating icon is actually hidden behind the button to activate rotation. Maybe a suggestion to position the green rotating icon never behind one of the buttons to control the interactivebox!

Will release a new minor version that would basically automatically hide the menu buttons when perform action so that the rotation button will not be overlapped.

**Comment by leijdekkers** [comment]
Sounds good. Actually it would be good to hide the buttens when you perform a rotate or resize action. The buttons or sort of in the way when you perform these actions.

**Comment by leijdekkers** [comment]
Thanks. Can confirm that it works beautifully. Makes it more intuitive for the user when they want to resize/rotate the image.
